### PR TITLE
Haikuports Recipe Syntax: WIP and not tested.

### PR DESCRIPTION
**Pull request by miqlas**
Keywords from Pe.

### CODE REVIEW

**Comment by miqlas** [comment]
Result: http://chunk.io/f/d47a2f89d7de4346b010120b8fb53cbd
Not perfect, but better than nothing.

**Comment by miqlas** [comment]
So it is already tested. Works ok.
@Kapix is there any problem with this PR?

**Comment by KapiX** [comment]
There is: you've used C++ lexer to parse bash. I have nothing against recycling existing lexers for other purposes, but C++ is too different from Bash for this to work properly (see comment lines).
If you can find a language lexer that is similar to Bash and supports more than one list of keywords, use it.
Otherwise I'd just use bash lexer for now (as a separate language, like it is now), and add keywords like SUMMARY to keywords list.
Also, you didn't delete recipe extension from bash language.

**Comment by miqlas** [comment]
I close this for now.

**Pull request closed without merging**
